### PR TITLE
MR-225 Can not import RDCMan v2.7

### PR DESCRIPTION
**Pull request by brucetp**
Referres to [#225](https://github.com/mRemoteNG/mRemoteNG/issues/225) & [#663](https://github.com/mRemoteNG/mRemoteNG/issues/603) 
I've modified the file import to be able to import from RDCMan v2.7 (while keeping the v2.2 in tact).   I also created all the test cases for v2.7.  I did modify the test_RDCMan_v2_7_schema3.rdg embedded resource because the properties in that file didn't match the v2.2 resource and thought the tests should be equivalent.   All tests pass.  Give it a try and let me know.  Thanks

### CODE REVIEW

**Comment by brucetp** [comment]
Well, I think the only reason this is failing is because I added a new file to the Test Project.   Let me know if there's something I need to do.

**Comment by sparerd** [comment]
This is weird - I don't know why it still thinks there is a merge conflict

**Comment by sparerd** [comment]
Ok, should be good now. I don't know why it still thought there was a merge conflict

**Comment by mpriesol** [comment]
Hello, thanks for this enhancement. 
I've just installed 1.76.0.25712 and tried import rdg from 2.7, but no success.
So I was testing a bit and found out, that the import doesn't support logon credentials saved to file. In other words, RDC manager offers an option to use saved profiles as a logon credentials. If you use these, it creates following entry in rdg file:
```
      <logonCredentials inherit="None">
        <profileName scope="File">domain\username</profileName>
      </logonCredentials>
```
If you use local credentials instead, additional tags are present, like password and domain.
```
        <logonCredentials inherit="None">
          <profileName scope="Local">Custom</profileName>
          <userName>myusername</userName>
          <password />
          <domain>mydomain</domain>
        </logonCredentials>
```
Technically, if mRemoteNG`s Import function doesn't find <domain> inside <logonCredentials> tag, it fails.
If domain tag is present, it will import data.

**Comment by anhlqn** [comment]
I deleted all the profiles in profile management and was able to import into mRemoteNG

**Comment by TiloGit** [comment]
can't import from 2.7 as well. try to modified the .rdg file but not luck. 
https://www.reddit.com/r/mRemoteNG/comments/9x1fm2/rdcman_27_file_import_fails/

> 2019-04-04 16:38:16,461 [1] ERROR - Error occurred while importing file 'C:\Users\tilos\Documents\TiloRDPs_TiloForImport.rdg'.
> Exception has been thrown by the target of an invocation.
> 2019-04-04 16:39:32,715 [1] ERROR - Error occurred while importing file 'C:\Users\tilos\Documents\TiloRDPs_w_domain.rdg'.
> Exception has been thrown by the target of an invocation.

**Comment by TiloGit** [comment]
I could import my 2.7 file after replace: 

```xml
<logonCredentials.*?</logonCredentials>
>>with (via NP++)
<logonCredentials> </logonCredentials>
```

**Comment by hubertsvk** [comment]
hi,
is the problem resolved? I have RDCman 2.9 and cant import.

**Pull request merged**
