### PR TITLE
Update .github templates

### PR DESCRIPTION
**Pull request by benwa**
Bumping up the quality of the templates with help from https://www.talater.com/open-source-templates

I figure more info is better than less

### CODE REVIEW

**Comment by sparerd** [comment]
Thanks for adding this @benwa! 

My comments didn't save from a few days ago.. i could have sworn they posted... :(
I don't remember all my comments so they must not have been all that important. Here's the one I do remember though:

What do you think about adding a quick description under each field? I saw it on an issue for either mstest or vstest recently though now I can't find it. It was a nice bit of extra prompting

Like:
# Steps to Reproduce
> Provide steps to reproduce the issue. Please be as detailed as possible.
1.
1.

**Comment by benwa** [comment]
The descriptions are there, but they're wrapped in comments. (check [line 16](https://github.com/mRemoteNG/mRemoteNG/pull/913/files#diff-1a1c3dd142f76a5fad803a0c52839881R16))  That way it will show for the submitter, but won't display on the submission.

Do you want them visible in the actual submission too?

**Comment by sparerd** [comment]
Ahh, I was looking at it in the rich-text view and missed all of that completely. I like it

**Comment by benwa** [comment]
Awesome.  If you have a few minutes, run through https://www.talater.com/open-source-templates. I answered to the best that I could and did slight tweaking to the output but want to make sure it's all correct for this project.

**Comment by sparerd** [comment]
The template on that site has a description field at the top. What are your thoughts on adding it to our issues template?

```
## Description
<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->
```

**Comment by benwa** [comment]
I think that one is if you chose bug only. I put bugs and feature requests. They're all over [here](https://github.com/TalAter/open-source-templates/tree/master/site/templates/issues)

**Pull request merged**
