### PR TITLE
Fix themes on installer version, initial menu position fix

### PR DESCRIPTION
**Pull request by jotatsu**
The 1.76 alpha installer is not working correctly as it is searching for the included themes in the ..user\appdata folder and not in the installer folder. This new patch auto copy the missing themes into the appdata folder . Redone the menu position so on the first run are not messed up.

### CODE REVIEW

**Comment by sparerd** [comment]
Looking good @jotatsu. Though I notice that with themes on, the checkbox check mark is a bit low. Is that related to this change or a separate issue?

capture

**Comment by sparerd** [comment]
Closing and reopening the options dialog causes an exception.

Stack trace:
```
   at System.Windows.Forms.Control.ControlCollection.get_Item(Int32 index)
   at mRemoteNG.UI.Controls.Base.NGNumericUpDown.OnCreateControl() in C:\Repos\mRemoteNG\mRemoteV1\UI\Controls\Base\NGNumericUpDown.cs:line 32
   at mRemoteNG.Themes.ThemeManager.ThemeChangedEventHandler.Invoke()
   at mRemoteNG.Themes.ThemeManager.NotifyThemeChanged(Object sender, PropertyChangedEventArgs e) in C:\Repos\mRemoteNG\mRemoteV1\Themes\ThemeManager.cs:line 219
   at mRemoteNG.Themes.ThemeManager.set_ActiveTheme(ThemeInfo value) in C:\Repos\mRemoteNG\mRemoteV1\Themes\ThemeManager.cs:line 262
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.cboTheme_SelectionChangeCommitted(Object sender, EventArgs e) in C:\Repos\mRemoteNG\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 127
   at mRemoteNG.UI.Forms.OptionsPages.ThemePage.LoadSettings() in C:\Repos\mRemoteNG\mRemoteV1\UI\Forms\OptionsPages\ThemePage.cs:line 72
   at mRemoteNG.UI.Forms.frmOptions.AddOptionsPagesToListView() in C:\Repos\mRemoteNG\mRemoteV1\UI\Forms\frmOptions.cs:line 87
   at mRemoteNG.UI.Forms.frmOptions.frmOptions_Load(Object sender, EventArgs e) in C:\Repos\mRemoteNG\mRemoteV1\UI\Forms\frmOptions.cs:line 33
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by jotatsu** [comment]
woot, will see

**Comment by jotatsu** [comment]
Ok round 6, to see if this works, ill not correct more tabbing bugs as i will go for the magic library remove first.

**Comment by sparerd** [comment]
I've taken a look at the changes and have run through some tests. I'm feeling decent about the changes and the jenkins build issue is minor (file wasn't removed from the solution - easy fix).

 Updated font looks better - check mark is centered in checkbox controls. Not seeing any exceptions from the options pages. I'm going to merge what we have so far in preparation for another v1.76 alpha release. Feel free to open another PR if there is more to add

**Pull request merged**
