### PR TITLE
App redesign proposal

### PR DESCRIPTION
**Pull request by farosch**
## Description
Replaced Images of the mRemoteNG logo and icon to a more flat design, matching the (btw awesome) homepage design. Added Photoshop templates for all images/icon created.

**-This is meant to be mere proposal at this point-
Please feel free to share your thought on this redesign!**

_I created a simple pixelated version of the icon to be used whenever the icon needs to be 16x16. The downscaled version of the logo I created doesn't look very well when downscaled to such a small size.
Maybe I need to change something about the Icon or maybe I was just too stupid to do a proper resize.
Here is the logo for anyone thats willing to teach me a lessen about poor design choices :P (if you need the psd-file you will have to [get it from my repo](https://github.com/farosch/mRemoteNG/tree/redesign/mRemoteV1/Resources/Templates))_
appicon

## Screenshots
Desktop Icon:

Windows 10 Tiles:
explorer_2018-12-24_00-24-08
explorer_2018-12-24_00-24-31

Splashscreen:

About screen:
mremoteng_2018-12-23_21-05-21

Mainform and Notify Icon:

Installer:
msiexec_2018-12-23_19-36-28
msiexec_2018-12-23_19-36-35

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kmscode** [comment]
@sparerd - Not sure 100% sure why the Jenkins build failed. But AppVeyor worked 😄 

I pulled the portal artifact from AV and gave it a quick run... I like the new look on the images.

I don't see any issues with a super quick code review. At this point (based on the visual changes), I'd be OK with merging this PR once the jenkins build issue is figured out. 

@farosch Thanks!!!!

**Comment by farosch** [comment]
Looks like you guys need to hurry up with #1210 😄

But jokes aside, the post build script `copy_tiles.ps1` seems to run fine and copied three new files(`mRemoteNG.VisualElementsManifest.xml`, `VisualElements_150.png` and `VisualElements_70.png`) to
`C:\jenkins\workspace\mRemoteNG_mRemoteNG_PR-1232-J7GRP7K5FOLRBMEQROZ7DM4HDRGCTSQHVTE6UVILEBRAJOIUJEDA\mRemoteV1\bin\`**Debug**`\`, but at the end jenkins tries to look for it in `C:\jenkins\workspace\mRemoteNG_mRemoteNG_PR-1232-J7GRP7K5FOLRBMEQROZ7DM4HDRGCTSQHVTE6UVILEBRAJOIUJEDA\mRemoteV1\bin\`**Release**`\`

Any ideas? I don't think that's something I can fix with changing my code..

**Comment by farosch** [comment]
[f2669bb](https://github.com/mRemoteNG/mRemoteNG/pull/1232/commits/f2669bb8753aa4235bf2988228ce5e064eb4782a) fixes #1235

**Comment by farosch** [comment]
[cbce572](https://github.com/mRemoteNG/mRemoteNG/pull/1232/commits/cbce5729fddc55bb6958e43b721ceed08f133e33) fixes #1236

**Comment by kmscode** [comment]
@farosch I fixed the jenkins build problem. See my commit: c0c699eab6453d552a93517b354b3497cf5a2d19

@sparerd Thoughts on this PR? - I like the more modern/flat icons. I think this is good to be merged currently.

**Comment by farosch** [comment]
@kmscode Thanks a lot! Seems like VS regenerated the solution file when I made some changes and threw this line away...

**Comment by sparerd** [comment]
In general I like the new flat icons, though I think we will want to fix the pixelated icon. We can either do that in this PR or do that in a new PR if it will take a while to research.

image

**Comment by farosch** [comment]
Oh, I haven't thought about that. I have set the "use small icons"-option on my taskbar so I didn't think about the fact, that normally windows will display a 24x24 version of the icon here.
Do you want to get rid of the pixelated version completely or should I provide the pixelated icon in multiple sizes like the normal one?

**Comment by farosch** [comment]
@sparerd I have removed the pixelated Icon - Tell me if you like this better.

**Comment by sparerd** [comment]
Yep, it fits in a little better now :)

image

**Comment by kmscode** [comment]
@sparerd I made one small change based on a problem that Otherwise, I think it looks great! Merging now.

**Pull request merged**
