### PR TITLE
Added czech localization file for mRemoteNG

### PR DESCRIPTION
**Pull request by rheingold**
The file was translated from the original Language.resx at the state of the current branch "develop". Just to not forget a few notes (maybe I might correct them later in a different branch/pull request):

Help (menu) -> Announcments (menu item) is not localized
Help (tab) -> tab title „Help“ is not localized according to the menu item „Help“
Tabs right click context menu -> Rename -> rename Dialogue -> OK/Cancel buttons are not localized accroding to the „strButtonOK“ „strButtonCancel“
Options (Settings) dialogue -> Tabs & Panels -> Use only Notifications panel (no messagbox popups) checkbox is not localized
Options (Settings) dialogue -> Advanced -> Write log file (mRemoteNG.log) checkbox is not localized
Components check tab -> Gecko (Fireforx) Rendering Engine section -> Descriptive text (succes) -> „Version“ label indetifikcation. The word „Version“ is not localized.
„Update“ tab -> „Check again“ button is not localized; Allways showing the same text („Check again“ – when the tab opens for the first time, it makes the impression the search for updates has allready been done)
„Update“ tab -> „Installed version“ label is not localized
„Update“ tab -> „Current version“ label is not localized; the difference of meaning of these two is not clear.
„Update“ tab -> „Version“ value label is not localized; 
„Update“ tab (when searching for updates finishes) -> „Installed version“ label is not localized
Helpfile localization / Writing not yet done (if I could help with the english as well with the Czech version, just give me a hint where to start)

### CODE REVIEW

**Comment by sparerd** [comment]
Hey @rheingold! Thanks for the PR, sorry it's taken so long for anyone to get back to you about it.

I plan on taking a look at it tomorrow (as long as nothing unexpected comes up).

**Comment by rheingold** [comment]
Ok, no problem, looking forward to it. Since I have no trouble with english, it does not matter which language has the UI, however it is somehow soothingly comforting to have the UI in my native.

 

WR

Lukas

 

Lukáš Plachý




Šaumannova 1, 61500 Brno, ČR

 <mailto:lukas@plachy.eu> lukas@plachy.eu

+420 603 113 469, ID DS: 4npengb

IČ: 76384195  DIČ: CZ8108063865

Zapsaný u ŽÚ města Brna, č.j. ZUMB/27637/2009/Jer/4

Československá obchodní banka, a. s.:  249 409 186 / 0300

**Comment by sparerd** [comment]
I think I steered you wrong when I told you to update the mRemoteNG.exe.config with the new `SupportedUICulture` entry. My bad :(

Could you update `mRemoteV1\app.config` to include `cs-CZ` in the SupportedUICultures entry?

Once this is done we should be ready to merge.

**Comment by rheingold** [comment]
uuhhhh, my fault, i did this locally in my binary config, but had forgotten to put it into the app.config, not familiar with the commit/push processes here.

**Pull request closed without merging**
