### PR TITLE
Moved searchbar in connection tree to top

### PR DESCRIPTION
**Pull request by farosch**
See #1216 
This is what it looks like:
image

### CODE REVIEW

**Comment by sparerd** [comment]
I think this is sensible - merging

**Comment by nmat** [comment]
Hmmmm shouldn't this be configurerable instead? For my eyes....it unfortunately gets cluttered in the top bar. :/

**Comment by farosch** [comment]
I wouldn't call five elements in two rows cluttered, but I think this should be fairly easy to implement if desired.
I initially just wanted to clean the UI a little bit without introducing more lines of code, but I guess I could give it a shot. @sparerd What do you think?

**Comment by nmat** [comment]
Oh I agree with the change. For _me_ its easier with it at the bottom. So I am only thinking about if it could be configurable. :)

**Comment by sparerd** [comment]
Usually I don't mind adding configuration options, though this one I'm on the fence about.

@nmat If the search bar was more visually distinct from the buttons, would that improve things? Or does it just feel weird that the search bar is at the top?

**Comment by sparerd** [comment]
That's fair. We can make it an option with the default set to bottom

**Comment by farosch** [comment]
That's how it looks atm

**Comment by sparerd** [comment]
That looks good - would you mind opening a new PR to add the config option?

**Comment by nmat** [comment]
thats perfect! thank you!

**Pull request merged**
