### PR TITLE
Add winbox

### LINKED ISSUE #1311: winbox as in new tab
Winbox 3.18         mRemoteNG 1.76.11.40592       Windows 10 Pro 10.0.17763.316

Winbox as a new window in the program will not show up after login. Only a gray screen remains.
I would like to correctly open the winbox in the program window and go to use Winbox.

Screen after successful login to Mikrotik
image

The window opens as a separate Winbox application.

### PR DESCRIPTION
**Pull request by Filippo125**
Integrate Winbox Client to manage routerOs devices

## Motivation and Context
Fix: #1311 & #1297 - Winbox process cannot be integrate in a tab.
Implement: #895 - Integrated winbox.exe clients are used to manage ROS devices

## How Has This Been Tested?
I test it, with some routeros devices.

## Screenshots (if appropriate):
winbox_property
winbox_all

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [X] All Tests within VisualStudio are passing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

# Before merge:
- [X] I have not succeeded to add source binary to project build, can someone fix it, please?
- [ ] Fix winbox icon style

### CODE REVIEW

**Comment by Filippo125** [comment]
Changed icon, but the look is not very well.
image

**Comment by Filippo125** [comment]
Checklist:
[x] I have read the CONTRIBUTING document.
[x] My code follows the code style of this project.
[x] All Tests within VisualStudio are passing
[x] This pull request does not target the master branch.
[x] I have updated the changelog file accordingly, if necessary.
[] I have updated the documentation accordingly, if necessary.

**Comment by Galandrix** [comment]
any chance that someone will fix it?

**Comment by Kvarkas** [comment]
its a bit outdated and hardly can be merged automatically, will be doing manual merge to branch 1.77.2-dev

**Comment by Kvarkas** [comment]
I give up trying integrate such, will maybe come back later as external module

**Pull request closed without merging**
