### PR TITLE
Updated GeckoFX

### PR DESCRIPTION
**Pull request by farosch**
## Description
Updated the geckofx nuget package from `geckofx45` to `geckofx60.32`

## Motivation and Context
#1460 

## Screenshots (if appropriate):
image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [X] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by farosch** [comment]
@sparerd Can you take a look at why the installer build fails?
`C:\projects\mremoteng\InstallerProjects\Installer\Fragments\FilesFragment.wxs(7602): error CNDL0044: The Class element's ForeignServer or Server attribute was not found; one of these is required.`
Looks like the FilesFragment.wxs doesn't get generated right...

**Comment by sparerd** [comment]
@farosch Will do

**Comment by sparerd** [comment]
Looks like we can add `-scom -sreg` to our call to heat.exe and it will suppress COM and registry harvesting, which was throwing the error. The Firefox component seems to still work, though installing took a very long time on my machine. Not sure if that was due to my change, or just a fluke. Would you be able to test as well? I will push my change now

**Comment by sparerd** [comment]
Scratch that, forgot my work is dumb and disables port 22 globally. No pushing to GitHub >:(

Here's the part we need to add to the Installer project's  build events:
image

**Comment by farosch** [comment]
Just pushed that fix, installer builds fine now! Thanks!
I have installed both installer builds (from VS and AppVeyor) both of them installed normally with no noticable difference in time!
I'll let my colleagues test this installer as well just to be sure.

When I don't notice any problems are you fine with me merging this pr?

**Pull request merged**
