### PR TITLE
bugfix for Putty import

### PR DESCRIPTION
**Pull request by RFC1920**
…rt setting

## Description
Fixed import of username and port, and also made hostname match the putty key name.

## Motivation and Context
bugfix

## How Has This Been Tested?
Re-ran import from registry after fix and confirmed hostname, username, and port.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Changed feature (non-breaking change which changes functionality)
- [ ] Changed feature (**breaking** change which changes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] All Tests within VisualStudio are passing
- [ ] This pull request does not target the master branch.
- [ ] I have updated the changelog file accordingly, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by savornicesei** [comment]
Hi @RFC1920 
I just have 2 observations:
1. Is there a reported bug that this PR fixes?
2. Is it possible to have some tests for the changed code?

Thanks

**Comment by RFC1920** [comment]
This is a fix for my previous pull request to implement putty import.  As for tests, I wouldn't know how to do that currently.

**Comment by Kvarkas** [comment]
@savornicesei  that for previus PR, its a new functionality not changing main code, but we dont have tests scenarios for such, will need to add later (not sure yet how exactly so will so far manual testing)

**Comment by simonai1254** [comment]
Not sure why I'm tagged here, didn't contribute anything here...

**Comment by Kvarkas** [comment]
oh sorry @simonai1254 you just one line below in the list, so selected in error :( I was replying to @savornicesei

**Pull request merged**
