### PR TITLE
facelift files

### PR DESCRIPTION
**Pull request by evilbaschdi**
some images are already changed. I also provided the VisualElementsManifest.xml.
Because of missing compoments I were not able to build the whole UI to see all of the changes.

https://twitter.com/mRemoteNG/status/930464358190198785

### CODE REVIEW

**Comment by sparerd** [comment]
Might be missing Citrix receiver? That's a common missing component. Here's the devenv setup doc if you need it:
https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment

**Comment by evilbaschdi** [comment]
that's correct. I hadn't installed it yet because I do not use it on my private computer.
Maybe I'll try it out later.

**Comment by sparerd** [comment]
Np, thanks for the PR

**Comment by farosch** [comment]
wouldn't it be more consistent, to use the same graphics as the mRemote-logo on the homepage?
e.g. something like this? (beware: quick and dirty)
2017-11-15 17_57_41-home _ mremoteng
I also think the two colors are a real distinct design element that people instantly associate with mRemoteNG and thus shouldn't get lost

Also these color would be better to fix issue #681

**Comment by farosch** [comment]
Same thing for the header:
logo

**Comment by kmscode** [comment]
@farosch You make good points, but I think the icons as submitted are still lighter than the current ones and would likely still address that PR.... Would need to play with it a bit.

@evilbaschdi Fantastic! Thanks!

Would it be possible to adjust header.bmp and Logo.png to have the text bigger and make better use of the space? Also for Logo, I think we'd still like the "Multi-Remote Next Generation" tag line. @sparerd what do you think?

Can you include any "source" files (psd, etc) within the PR?

@sparerd If I recall correctly, we need .bmp's for the installer. It doesn't accept other image formats, correct? Otherwise I would say we should standardize on png except where an ico is required.

**Comment by farosch** [comment]
#806 Since I was bored, here's another PR so you guys can have a look at what I have in mind.

**Comment by kmscode** [comment]
closing this PR in favor of #1232 which includes additional changes and source image files (PSDs).

**Pull request closed without merging**
