### PR TITLE
Configurable Backups

### PR DESCRIPTION
**Pull request by padillah**
Added features to expand backup frequency and path, and implement changing the max backup count.

## Description
* Added controls to ConnectionsPage and added code that expanded the kinds of backup frequency available.
* Added custom class to allow for dropdown to enumerate the backup frequency.
* Added controls and code to set the backup path. reused code from SaveAs in effort to remain consistent. Backup path is still attached to the connection file. This may not be ideal.
* Added controls and code to set the Max Backup count. Now that this is set the FileBackupPruner handles the pruning.

## Motivation and Context
Fixes issue [#474](https://github.com/mRemoteNG/mRemoteNG/issues/474)

## How Has This Been Tested?
Tested as new install:
 - Opened and closed options page saving several times.
 - Checked timings of the backup files to ensure they do not get created unless time has elapsed.
 - Changed backup path several times to ensure it gets reloaded correctly.
 - Changed backup path and closed and opened to ensure new path  gets loaded correctly.
 - Saved several backups to ensure no more than the Max Backup count get created.

Tested as upgrade:
 - Copied new dlls to current installation and ran.
 - Opened and closed options page saving several times.
 - Checked timings of the backup files to ensure they do not get created unless time has elapsed.
 - Changed backup path several times to ensure it gets reloaded correctly.
 - Changed backup path and closed and opened to ensure new path  gets loaded correctly.
 - Saved several backups to ensure no more than the Max Backup count get created.

## Types of changes
- New feature (non-breaking change which adds functionality) 

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [X] All Tests within VisualStudio are passing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [X] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by sparerd** [comment]
@farosch Do you still have a local branch with this code? I tried to apply the patches but it's giving me a lot of trouble.

**Comment by farosch** [comment]
@sparerd Unfortunately I do not..

**Comment by padillah** [comment]
I do have a local copy as well as the original fork still alive and untouched. Let me know if this is still needed.

**Comment by farosch** [comment]
Hey @padillah 
Could you maybe revive that _474_Configurablebackups_ branch or maybe create a new PR with your changes?

**Comment by padillah** [comment]
@farosch , yeah. Give me a couple of days.

**Review by Kvarkas — APPROVED** [review]

**Review by Kvarkas — APPROVED** [review]

**Comment by farosch** [comment]
Closing this PR, as we no longer have access to the code (source branch has been deleted).
@padillah We would really like for you to resubmit this PR! If you still have access to the code just push it again and don't wory about all the merge issues - I will take care of them.

**Comment by Kvarkas** [comment]
am almost finished manually add all this changes :)

**Comment by padillah** [comment]
I am so sorry!! Somewhere GitHub emails got pushed to spam. I think this one showed up because it mentioned me specifically or something.

~Do you want me to just re-push? Or should I create a second fork, rebase onto that second fork, and then push that?~

Strike that. I checked and it looks like I deleted that fork. I can recreate a good sized chunk of it but there are some icons I don't think I can replace.

**Comment by Kvarkas** [comment]
@padillah no worries about icons, wait a bit, I almost include all changes into, will commit this week to develop branch, then you perhaps can recheck and fix/add if I miss something. Icons we can replace later not very important.

**Pull request closed without merging**
