### PR TITLE
Added code and screenshots for Quick Connect help files

### PR DESCRIPTION
**Pull request by ForensicITGuy**
Added HTML code and screenshots for Quick Connect help file documentation. Related to Issue #216

### CODE REVIEW

**Comment by sparerd** [comment]
Thanks for the PR!

I just have 1 thing for you to fix, then we can accept it:
- Currently, the new screenshots are not tracked by mRemoteV1.csproj. Make sure that the Screenshots/QuickConnect/*.png files are being tracked as content items and that they are set to copy to the output directory (copy if newer). (This last part is key, otherwise the screenshots won't exist when we build the program.)

I can help out if needed - just let me know.

**Comment by ForensicITGuy** [comment]
No problem, I'll give it a go. I haven't done that kind of contribution before, so I need to set up a dev environment tonight to manipulate the project.

**Comment by sparerd** [comment]
Good deal - we have dev environment requirements posted up on the wiki if needed.
https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment

**Comment by ForensicITGuy** [comment]
The latest commit should be the most accurate one. Content has been added in to the VS project and I modified folder names/image paths to include spaces like the others for consistency. Please let me know if any more is needed for this PR.

**Comment by sparerd** [comment]
Looks good - accepting this PR

**Pull request merged**
