### PR TITLE
Support for Hyper-V VMRDP

### PR DESCRIPTION
**Pull request by farosch**
Replaces #1179 

## Description
This allows for mRemoteNG to connect to a virtual machine via rdp by only talking to the hypervisor hosting the vm. This makes it possible to connect to hyper-v virtual machines that reside in an isolated network or don't have a network connection at all.

Introduced two new connection properties only visible for protocol type rdp:
-Use VM ID (bool)
-VMID (string)

## Motivation and Context
#1179 and #316

## How Has This Been Tested?

Successfully connected to vm running on the same machine as mRemoteNG and running on another server in a different domain.
Client: Windows 10 Professional 1903 18362.53 / Server: Windows Server 2012R2 6.3 9600
Server: Windows Server 2012R2 6.3 9600

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by sparerd** [comment]
The previous PR had what was called an `EnhancedSession` option which included some extra text in the PCB. Are you planning on also adding this option? (Not sure what it does)

**Comment by farosch** [comment]
The [Enhanced Session Mode](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect) allows for local resources to be redirected to the hypervisor, just like in RDP.
I'll update the PR to automatically enable enhanced mode when connecting via a PCB.
Since all redirects (keyboard, printers, etc) have to be enabled seperately theres (imho) no need for an extra enhanced mode option.

**Comment by sparerd** [comment]
@farosch That makes sense, thanks for looking into it.

**Comment by tboege** [comment]
I have just tested this huge improvement in the latest preview. But I have one problem: Sometimes I need to be able to use the vmconnect in standard mode - not enhanced mode. And other VM's I have to use enhanced mode. As I read above, it is not possible to select standard mode. Is it possible to get that feature?

**Comment by farosch** [comment]
@tboege Sure, this could be implemented.
Could you explain what difference it makes if you connect in `default mode` or `enhanced mode`?
Couldn't you just enable enhanced mode but not redirecting any device? 🤔

**Comment by tboege** [comment]
I need it for a workaround for cisco anyconnect vpn. If I try to connect in enhanced mode, anyconnect fails (I think it detects its in an rdp-session (not entirely wrong), and the security settings forbids a connection). In default mode, I have no problems (with that).

I have tried in enhanced mode with no redirection of devices, but I still cannot connect with anyconnect.
So I think the only solution to make it work is to use default mode

**Comment by farosch** [comment]
@tboege That makes sense.
I have created a new issue #1564 tot rack this.
Will add this option back in the days to come :)

**Comment by tboege** [comment]
Thank you. Unfortunately I downt know how to build a new  version from source, so I have to wait for a new prerelease to test it out and provide feedback.

**Comment by smabcy** [comment]
anyone using vmid vmrdp has this? thanks!
----------
WarningMsg
09/07/2019 12:35:19
Protocol Event Disconnected. Host: "192.168.135.144"; Protocol: "RDP" Message: "An internal error has occurred."
----------

**Comment by TNT911** [comment]
You may want to also look into the importing of .RDP files.  I tried to import one create by Hyper-V's export .rdp feature.  The file includes the VM ID etc.  However, once imported, it did not enable VM ID, fill out VM ID, and RDP Version would need to be adjusted.
Keep up the good work!

**Comment by davi1td** [comment]
Hi, so far this is working great for me! Thanks for an awesome app!
However I have one VM - > Pfsense - > freeBSD, doesn't work, when I try to connect the screen just flashes connecting rapidly forever. If I try several attempt it eventually hoses the app and have to restart. 
Thanks
-TD

**Comment by tboege** [comment]
I am quite sure, that enhanced mode needs support in the guest operating
system, since it is some kind of rdp connection, the operating  system
needs to support that. I think, that there are some support in Ubuntu, but
I dont think it is supported in pfsense/freeBSD.

Of couse, mRemoteNG should not crash whether enhanced mode is supported or
not.

Den lør. 14. dec. 2019 kl. 20.24 skrev TD <notifications@github.com>:

**Comment by davi1td** [comment]
Hmm, not sure "Enhanced" mode applies here. Either way all things equal, the only settings enabled are:
Use VM Id: yes
VM Id: the guid for the hyper-v
Hostname: localhost
port: 2179
Error occurs whether use console session is yes or no.
My confusion here is Virtual Machine Connection in Hyper-v Manager connects to it just fine. 
I did try to debug from source but could not find where that generic internal error is coming from.
Pfsense uses FreeBSD which is supported to some degree : [Supported FreeBSD virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-freebsd-virtual-machines-on-hyper-v)
Thanks
-TD

**Comment by kklliu** [comment]
Hi, I am using v1.77.1 version and trying to use VMRDP function.

I am quite sure all the prerequisites are all set, since I can connect Hyper-V VM via Microsoft RDCman, like the pic below.

Screen Shot 2019-12-31 at 1 10 59 PM

However, when I tried to use mRemoteNG, which is setup like below, to connect, 
Screen Shot 2019-12-31 at 1 15 37 PM
I got an immediate error, like this:
Screen Shot 2019-12-31 at 1 24 38 PM
means:
Protocol Event Disconnected. Message: "An internal error has occurred."

The mRemoteNG.log shows (**I try to translate Traditional Chinese to English**)

> 2019-12-31 13:03:21,880 [1] INFO  - 設定(Setup) RDC 10.0.17134 的 Console 開關(Switch)。
> 2019-12-31 13:03:21,880 [1] INFO  - 支援(Support) RD Gateway。
> 2019-12-31 13:03:21,896 [9] INFO  - Saving connections...
> 2019-12-31 13:03:22,005 [9] INFO  - Successfully saved connections
> 2019-12-31 13:03:22,052 [1] WARN  - Protocol Event 已中斷連線(Already Disconnected)。
> 訊息(Information):
> 發生內部錯誤(An internal error has occurred)。
> 2019-12-31 13:03:22,146 [5] INFO  - 連線事件已關閉(Connection Event Closed)
> 2019-12-31 13:03:22,146 [5] INFO  - 使用者「xxx」關閉透過「RDP」連線到「x.x.x.x」。
> 2019-12-31 13:03:22,162 [18] INFO  - Saving connections...
> 2019-12-31 13:03:22,271 [18] INFO  - Successfully saved connections
> 

Could you please tell me what should I do?
Thanks a lot.

**Pull request merged**
