### PR TITLE
Move CHANGELOG.TXT to CHANGELOG.md

### PR DESCRIPTION
**Pull request by benwa**
## Description
for #1310
Changes CHANGELOG.TXT to CHANGELOG.md, as well as CREDITS.TXT

## Motivation and Context
By switching the extension-since the changelog is already using markdown formatting-when viewed in GitHub, it'll render correctly. It would also follow other projects naming (see https://keepachangelog.com/en/1.0.0/#filename).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by farosch** [comment]
We should probaby sneak in a fix for #1153 with this pr, too

**Comment by nmat** [comment]
> We should probaby sneak in a fix for #1153 with this pr, too

IMO I kind of feel like we can implement this already. It is a improvement. Just need to be sure that there are no other problems with the merge.

**Comment by benwa** [comment]
Looks like the installer will need to be updated too https://ci.appveyor.com/project/mremoteng/mremoteng/builds/23982558/job/viv7nk8u8kxqu706#L1416

Not sure how to go about that one, maybe @kmscode can help?

**Comment by sparerd** [comment]
I could update the installer - would someone be able to resolve the merge conflicts? Not sure what changes were made in the AboutWindow that would need to be preserved.

**Comment by sparerd** [comment]
The installer is updated - we good to merge? @farosch @benwa

**Comment by benwa** [comment]
I think we're good unless there's some styling you want to do to it.

**Comment by sparerd** [comment]
Nope, I think the styling is good as is. Thanks for the PR @benwa!

**Pull request merged**
