### PR TITLE
Replace GeckoFX with CefSharp

### PR DESCRIPTION
**Pull request by leaskovski**
Added the CEFSharp component to the project. ~~This is a Web rendering engine that is based on Chromium meaning that as well as being able to use IE and Gecko (Firefox), users will now also have the option to use CEF (Chromium) as their rendering engine.~~ This is a Web rendering engine that is based on Chromium meaning users will be able that as well as being able to use IE and Chromium as their rendering engines.
This will mean the use of Chrome Remote Desktop as a URL can be used to provide connections to machines that use this protocol.

## Description
Added a new option to "Rendering Engine" called "CEF (Chromium)".  This requires CEF Sharp as being added to the project via nuget, and add a chromium based rendering engine to the application.
This covers the feature request #1071

## Motivation and Context
Chrome Remote Desktop is a protocol provided by Goolge to allow remote connections to machine.  This can be accessed via a website (https://remotedesktop.google.com/access), however this site (being Google) doesn't play well with other browsers, so neither the IE or Gecko engines work.  By adding CEF, the site renders fine and allows connections to machines hosted under this tool.

## How Has This Been Tested?
Basic testing has been completed by using the new engine for the original mentioned use case of Chrome Remote Desktop.
Tested under Windows 10 and Windows 7 environments.
Tested using Portable build only.
Tested persistence of logins to to site mentioned above.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] This pull request does not target the master branch.
- [x] I have updated the changelog file accordingly.
- [X] My change requires a change to the documentation, if necessary.
- [X] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by farosch** [comment]
First of all thank you very much @leaskovski for this PR! 

@sparerd @kmscode 
I would much more prefer to implement chromium **exclusively** into mremoteNG. What do you guys think about this?
-The IE based web browser control is nightmarish wehen it comes to security vulnerabilities. Even Microsoft itself does not recommend using IE anymore
-Chromium has the highest compatibility
-Chromium uses the Microsoft Certificate Store which makes it easier for system administrators to handle trusted certificates, especially when they come from a Windows Certificate Authority
-There is no real benefit (at least to my knowledge) that comes with choosing between different HTML rendering engines
-Simplification of code

**Comment by farosch** [comment]
I have decided to close #1761 because IE support might still be needed by users to maintain legacy hardware. There's absolutely no reason to have both GeckoFX and CefSHarp build into mRemoteNG  though - There is no real benefit to it and shipping with both rendering engines would blow up the size of mrng.

**Comment by farosch** [comment]
@leaskovski I've added a download handler to handle file downloads in cef and also added a link handler, so that I could use cef for the help window also.
This allowed me to completely replace gecko with cef.
Does this look good to you? Any suggestions for improvement?

**Comment by leaskovski** [comment]
@farosch just looking over the code.  Tried to run it on my dev system and it chucks an error because of the help files not being located.  Is help excluded for the portable versions of the software?  Might be worth putting an file space check around that loading?

**Comment by farosch** [comment]
@leaskovski I think the Firefox folder you still see in your output folder is left over from previous builds.
Use _Build_ > _Clean Solution_ from within VS before building this branch.
I don't have a Firefox folder in any build and Accessing the help files works just fine for me in every build, too.
I think you get that error simply because you haven't set up your environment properly and the help files don't get build on your system.
Check this page out: 
https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment

**Comment by farosch** [comment]
@leaskovski
Whenever someone deletes the _Help_ folder from within the mrng directory they will be greeted with a runtime error upon opening mrng.
I'm pretty sure I could program a check around that and disable the help button when the directory cannot be found on startup.
On the other hand users could delete any other file from the directory also, which would result in some other error that is not handled.
I'd just go with the statement that everyone that deletes folders from a programs' directory will have to live with the consequences that come with it.
I don't delete my system32 folder and bame microsoft for the results, either...

**Comment by leaskovski** [comment]
> @leaskovski
> Whenever someone deletes the _Help_ folder from within the mrng directory they will be greeted with a runtime error upon opening mrng.
> I'm pretty sure I could program a check around that and disable the help button when the directory cannot be found on startup.
> On the other hand users could delete any other file from the directory also, which would result in some other error that is not handled.
> I'd just go with the statement that everyone that deletes folders from a programs' directory will have to live with the consequences that come with it.

I totally understand your sentiment on this.  If users don't have complete distributions, then they should expect errors.  The only thing is, I just downloaded the portable package from https://mremoteng.org/download, and that doesn't contain a "Help" folder, hence why i was wondering if the build process for the portable builds needs updating?

**Comment by farosch** [comment]
You're right, the prerelease doen't contain the Help files.
This does not have anything to do with this PR though, the last prerelease is from Mon, Sep 02, 2019.

**Pull request merged**
