### PR TITLE
Fixes settings save location on portable version

### PR DESCRIPTION
**Pull request by pedro2555**
This is reported on [issue#487](https://github.com/mRemoteNG/mRemoteNG/issues/487)

The portable version doesn't actually save the settings within the application folder, making it not truly portable.

This implements [crdx's `PortableSettingsProvider`](https://github.com/crdx/PortableSettingsProvider), and a custom provider chooser class that basically shifts implementation based on the compile time const `PORTABLE` to implement, either `PortableSettingsProvider` class, or the .NET default `LocalFileSettingsProvider` class.

A local Settings class had to be explicitly declared in order to decorate it with the new provider.

From the code I could see, this was attempted in the exact same way before, but with no success. I did not try to fix the existing code because [crdx's `PortableSettingsProvider`](https://github.com/crdx/PortableSettingsProvider) simply works.

### CODE REVIEW

**Comment by pedro2555** [comment]
Fixes:
#487 
#414
#690

**Comment by kmscode** [comment]
I'm not 100% sure if we want to make this change in a patch release. Though I think it would be received well by the user base... So this one will likely sit open a bit longer I'm afraid.

**Comment by pedro2555** [comment]
Should be an easy merge, whenever you do it.

**Comment by penguinairlines** [comment]
Thanks for this.  I was wondering why the portable version wouldn't save settings.  The information where it currently saves is also valuable for backups.  I hope to see the suggested change implemented at some point to this otherwise fantastic application.

**Comment by sparerd** [comment]
Tasks for myself to get this merged:
- [ ] Update [User settings file](https://github.com/mRemoteNG/mRemoteNG/wiki/User-settings-file) with new file path info for portable version >=1.76
- [ ] Update [Acceptance Testing](https://github.com/mRemoteNG/mRemoteNG/wiki/Acceptance-Testing) with test cases for this change

**Comment by sparerd** [comment]
Also, retargeted to `develop` branch for inclusion in v1.76

**Comment by sparerd** [comment]
Resolved merge conflicts due to retargeting to `develop`. 

@pedro2555  I did a bit of quick testing and things look good. You might want to retest again yourself to make sure I didn't mess anything up

**Comment by sparerd** [comment]
Testing still looks good - merging changes

**Pull request merged**
