### PR TITLE
 503 SSH Execute a single command after login 

### PR DESCRIPTION
**Pull request by merarischroeder**
## Description

- New property for SSH "Opening Command"
- After Putty is logged in, the Opening Command is written to Putty using `SendKeys` as well as the `\n` newline

## Motivation and Context

see https://github.com/mRemoteNG/mRemoteNG/issues/503

This makes it possible to create Connections for the purpose specific tasks on a host. 

It also opens the door to "Canned Commands" in the future. Where a stored command (global or per-connection) might be used by the user.

## How Has This Been Tested?

- Testing of Opening Command
- Visual Studio 2022 wasn't working well for this project. So I'm using VS2019 Community Edition.
- Once it's finished, this should be tested with `cd /var/log/` or something to prove it works.

## Screenshots (if appropriate):

image
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Changed feature (non-breaking change which changes functionality)
- [ ] Changed feature (**breaking** change which changes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] All Tests within VisualStudio are passing
- [x] This pull request does not target the master branch.
- [x] I have updated the changelog file accordingly, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by merarischroeder** [comment]
I think it's ready for merging. I'm not sure about the tests. I haven't created any.

**Comment by merarischroeder** [comment]
Yeah, it looks like there are a few tests to resolve pertaining to saving/loading configuration

eg: `Extra (1): < "OpeningCommand" >`

**Comment by Kvarkas** [comment]
we have include tests into project, with appveyour do a check if they pass or not, you can run them locally by run tests, currently 199 are failing, need to be sure we fix these before merge

**Comment by Kvarkas** [comment]
will fix issue with testing I think today

**Comment by merarischroeder** [comment]
Sure @Kvarkas, just cherry pick it

**Comment by Kvarkas** [comment]
@merarischroeder FYI I set OpeningCommand to be "" by default, that allow us to avoid failure on serialization then its not defined by user.
Perhaps we may need include definition into options if user would like to have same command by default for they connections...

**Comment by merarischroeder** [comment]
@Kvarkas 

>I set OpeningCommand to be "" 
(see commit https://github.com/mRemoteNG/mRemoteNG/commit/018979d17faa611482416bf7a3e4335667d6a48a, https://github.com/mRemoteNG/mRemoteNG/commit/19e6d37b6292253cea293c494656e30fd172cb6c, https://github.com/mRemoteNG/mRemoteNG/commit/cea5f57c6069ca31a1eebc9e3c6a44a5212891f9, https://github.com/mRemoteNG/mRemoteNG/commit/1e4dcc23d70a379286a41a4b661da8853ac6ef1f)

Good point, that's important to have as a minimum.

For completeness, I recommend also adding the If-Block, because now there will be a change in behavior for everyone. There will be an additional New-Line upon every Putty connection. Even if you are not using the feature.

**Pull request merged**
