### PR TITLE
Feature/remote desktop services

### PR DESCRIPTION
**Pull request by johnwc**
Added Alternative Shell property, will add others as well.

## Description
Added Remote Desktop Service group, to include Alternative Shell properties

## Motivation and Context
Adds one of the properties requested here. #327 

## How Has This Been Tested?
Tested locally against server with RDS enabled.
Tested MySql settings reading/writing

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [ ] All Tests within VisualStudio are passing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by mbrownnycnyc** [comment]
@benwa @sparerd  @kmscode  @farosch 

Can this be merged into the next experimental release?

**Comment by eckard** [comment]
Hi John, I've checked out your branch https://github.com/johnwc/mRemoteNG/tree/feature/RemoteDesktopServices and tested sucessfully with CyberArk. Would love to see this feature in the officcial build, is there a way to help getting this done?
Seems like the continuous-integration checks fails and therefore the merging into current 1.77 development is blocked by the project admins - or am I missing something here? How can we support to get this into the next release?

**Comment by farosch** [comment]
@mbrownnycnyc We'd be glad to merge this into develop, but unfortunately this PR is only half done for the reasons @eckard explained above, so it can not be merged as of now.
If @johnwc or somebody else will fix this PR, we will for sure include it in the next preview, but do not count on anyone from the core development team to pick up half finished PRs, as our time already is very limited.

**Comment by reox22** [comment]
I have check the branch of john 
branch https://github.com/johnwc/mRemoteNG/tree/feature/RemoteDesktopServices 
the fix for the no persisted save of the xml is 
in mRemoteNG\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionNodeSerializer27.cs
add 2 lines in 59-60.
57          element.Add(new XAttribute("Id", connectionInfo.ConstantID));

            element.Add(new XAttribute("StartProgram", connectionInfo.StartProgram));
            element.Add(new XAttribute("StartProgramWorkDir", connectionInfo.StartProgramWorkDir));
61            if (!Runtime.UseCredentialManager)
            {

this work well, tks john we will can use mremotemg with cyberark
@eckard or farosh can you confirm this fix.

**Comment by johnwc** [comment]
All has been update and merged from parent fork. As it did originally, the CI build in AppVeyor is passing both builds for the app but failing for installer. I did not touch anything in the installer, so I have no reason to debug why it is failing the installer build step. I can only assume the issue existed from the parent fork.

This PR is fully ready to merge as of today.

**Comment by Kvarkas** [comment]
@johnwc thanks! Installer fail due there is no official wix for 22 studio so added manually and its not manage to build it properly but I am awaiting they should release it soon so that will be fixed :)

**Pull request merged**
