### PR TITLE
Implementation of MySQL support

### PR DESCRIPTION
**Pull request by mjbnz**
Implementation of MySQL support

## Description
- Uses MySQL Connector/NET from nuget
- Adds SQL Server type to configuration.
- Hostname for MySQL connections can include port.  Format:  `<hostname>[:<port>]`
- Abstracted a bundle of stuff to be generic for both MSSQL and MySQL, including a number of variable and method names. (Mostly went from "sql..." -> "db...")
-  Changed MiscTools.DBDate() string building for MSSQL, uses DateTime.ToString() with a format which seemed simpler.
- Unsure about which lines in .csproj are actually required, and which are auto-munged by Visual Studio.
-  ... This is my first C# (and VS!) work, be gentle!

## Motivation and Context
I wanted mysql support - I'm fed up with how slow the current remote admin tool is we use, but to
replace it I needed something that supported mysql so we can share a connection database.
#925 #182 

## How Has This Been Tested?
Just by me getting it working, then adding connections and folders to the database.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
   * does have one case of nested usage of using(), but I'm new to C#, so not sure how to avoid that.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by sparerd** [comment]
Thanks for putting this together @mjbnz! Just took a quick look through the changes and things look pretty good. I wanted to give you a heads up that a few DB changes are being introduced in v1.76.12. I will be merging them to the develop branch in the next day or so. It introduces the ability to save certain properties locally rather than to the DB (#1180).

**Comment by mjbnz** [comment]
No problem, I'm happy to keep working on this. I would specifically like to start looking at having updates be written to individual entries, rather than dropping and refilling the table every time.

What branch are the database changes in?

**Comment by sparerd** [comment]
> I would specifically like to start looking at having updates be written to individual entries, rather than dropping and refilling the table every time.

I agree, that has always bothered me. Have you worked with Entity Framework before? I would like to redo the DB functionality in EF Core. It will allow us to handle DB migrations easily, add support for more database types relatively easily, and provide a fairly easy way to do CRUD operations in code.

**Comment by mjbnz** [comment]
No, but looking at it, it seems quite straightforward to implement. I'll make a start.

**Comment by sparerd** [comment]
@mjbnz I would suggest doing any larger improvement work under a new branch and PR - we will keep this one just for the MySQL implementation in its current state.

**Comment by mjbnz** [comment]
Yep, was planning to.

**Comment by sparerd** [comment]
@mjbnz The changes are now merged into master - pull from upstream for the latest. Let me know if you have any questions about the changes

**Comment by mjbnz** [comment]
@sparerd haven't had a chance to have another look at this yet, but I will do - sorry for the delay.

**Comment by sparerd** [comment]
No problem @mjbnz, thanks for checking in

**Comment by thewreckingcrew6** [comment]
Is this a goal for the 1.77 update? Or is this going to be implemented soon?

As far as I can tell currently the only way to do this is through Microsoft SQL server.

**Comment by sparerd** [comment]
@thewreckingcrew6 It will likely be in v1.77. We currently do not have a release schedule for v1.77 though. It is in early development

**Comment by thewreckingcrew6** [comment]
Sounds like a plan. No rush on it, but it's an awesome feature request. Absolutely love this program though.

**Comment by sparerd** [comment]
Hey @mjbnz, hope you are having a good holiday season. Just checking in to see if there is anything I can do to help with this PR

**Comment by mjbnz** [comment]
> Hey @mjbnz, hope you are having a good holiday season. Just checking in to see if there is anything I can do to help with this PR

Sorry - haven't looked at it in a while, you indeed did catch me on my holiday break! I'll look at this in the coming days/weeks.

**Comment by mjbnz** [comment]
Going to re-submit this from a different branch than develop.

**Pull request closed without merging**
