### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by Mant1kor**
## Description
I translate all untranslated strings and fix errors

## How Has This Been Tested?
I've been trying to test it by following instruction. But UI been always in English.
**So, need help with testing!**

## Types of changes
- [x] Updated translation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] All Tests within VisualStudio are passing
- [x] This pull request does not target the master branch.
- [x] I have updated the changelog file accordingly, if necessary.
- [x] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by farosch** [comment]
@Mant1kor You can pull the build from here to test it:
https://ci.appveyor.com/api/buildjobs/50m9xtmokuqxb7dj/artifacts/Release%2FmRemoteNG-Portable-1.77.1.32540.zip

**Comment by Mant1kor** [comment]
@farosch Seems like it works correct, but I need some time to fix several incorrect sentences.

**Comment by farosch** [comment]
No worries. Just keep pushing your changes to this branch.
It will then automatically get build and you can pull the artifact from appveyor to test it.
If you need any help, just ask! :)

**Comment by Mant1kor** [comment]
@farosch I've completed the translation.
And there is one bug with newline in CREDITS.md, can't fix this on my own.
зображення
Second issue I reported in #1610

**Comment by farosch** [comment]
I'll merge this PR into develop ASAP!
Thanks for your work! :)

**Pull request merged**
