### PR TITLE
Add show/hide main menu function to connection tree toolbar.

### PR DESCRIPTION
**Pull request by wangxuepeng**
## Description
Added shortcut function "Show/Hide Main Menu" under connection tree toolbar.

## Motivation and Context
Want to enlarge the content window to maximum while not want to enter full screen mode.

## How Has This Been Tested?
Tested manually with multiple windows and different languages.

## Screenshots (if appropriate):
screen shot 2019-03-08 at 10 35 21
screen shot 2019-03-08 at 10 35 29

## Types of changes
 - New feature (non-breaking change which adds functionality)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [X] All Tests within VisualStudio are passing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [x] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by kmscode** [comment]
@sparerd This look OK to merge after a quick review.  What do you think?

The Jenkins failure looks like to be a Jenkins problem, so nothing concerning there...

**Comment by farosch** [comment]
@kmscode code-wise it looks ok but ui-wise it'll cause at least one problem:
image

**Comment by farosch** [comment]
I would put an option like this into the windows application menu or whatever it's called:
mRemoteNG_2019-03-16_11-47-45


Also this should be changed from an option to hide the main menu into an option to hide the whole menu strip container

**Comment by wangxuepeng** [comment]
> I would put an option like this into the windows application menu or whatever it's called:
> mRemoteNG_2019-03-16_11-47-45
> 
> Also this should be changed from an option to hide the main menu into an option to hide the whole menu strip container

This idea is awesome!!

**Comment by nmat** [comment]
@farosch what is the status of pushing this to the next 1.77 build?

**Comment by farosch** [comment]
@nmat I'd like @sparerd and @kmscode opinion on this before merging anything because I don't really like either of these two approaches to hide the main menu..

**Comment by 2pascal** [comment]
Even if the implementation isn't ideal, could a fork be compiled with these changes for the group of users that wouldn't mind?

**Comment by farosch** [comment]
> Even if the implementation isn't ideal, could a fork be compiled with these changes for the group of users that wouldn't mind?
Yes, this is absolutely possible. mrng is an open source program and everyone can fork it and release their own modified version of it if they want to.
But we will never do this - A feature either gets implemented or it doesn't. There is one version of mrng only and it'll stay that way.

**Comment by farosch** [comment]
Sorry for the long wait guys - merging atm...
Thanks again to @wangxuepeng for the original PR!

**Pull request merged**
