### PR TITLE
external connectors update

### PR DESCRIPTION
**Pull request by tecxx**
add new connection panel fields for external connectors (currently only secret server)
image

add ec2 instance connector. this allows to fetch ip address from aws ec2 instance id dynamically before connection
image

## Description
added new properties for the fields api id, ec2 instance id, ec2 region
added language fields and config xml save/load code

## Motivation and Context
improve external connectors functionality by providing option fields instead of "SSAPI:" workarounds. 

## How Has This Been Tested?
using it in production

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Changed feature (non-breaking change which changes functionality)
- [ ] Changed feature (**breaking** change which changes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

### CODE REVIEW

**Comment by tecxx** [comment]
@Kvarkas could i get a short feedback why this was rejected? thanks.

**Comment by Kvarkas** [comment]
Hello, I wasn't reject that, has been approved merge, not sure why its so, let me check

**Comment by Kvarkas** [comment]
have no idea why, its not allow me to reopen :(

**Comment by Kvarkas** [comment]
could you try to reopen as author or submit a new one?

**Comment by tecxx** [comment]
actually it was good that it failed. i found a bug in the ec2 connector :) will fix it later and make another PR. thanks.

**Pull request closed without merging**
