### PR TITLE
Migrate Project to .NET6

### LINKED ISSUE #1705: "Build Request" Migration to .Net Core
I saw that mRemoteNG is based on C# and Powershell both of them have a new framework called .NetCore/powerhsell core which works on Linux, Mac and for sure on Windows. Wouldnt be a nice idea to change to this framework to build also this awesome program on linux and mac?

### PR DESCRIPTION
**Pull request by farosch**
## Description
This version of mRemoteNG has been ported to dotNET 6. Use VS 2019 Preview to build this project.
There are still a few issues that needs to be addressed but builds generally are very usable:
[Build status](https://ci.appveyor.com/project/mremoteng/mremoteng-dotnet)

**This branch will not be merged into develop before Microsoft has released a LTS version of .NET6.**

Not all tests within VS are passing at the moment, due to the following error: `System.TypeInitializationException: The type initializer for 'mRemoteNG.UI.Forms.FrmMain' threw an exception.` I guess this has something to do with the `STAThread` attribute not working as expected in .NET5, but this will need further investigation.

This branch was created by squash merging from #2006 and recommitting the changes made for easier understanding. (There was a lot of trying out on my side in #2006 which made it really hard to see what has really changed in the code and why.)

## Motivation and Context
Having mRemoteNG running on .the latest .NET allows us to be more open to new technologies and to profit from future developments.
This would also resolve #1705, and it could be another step towards #308.

## How Has This Been Tested?
This has been tested by me personally using it at work for about 4 Weeks now. I have not noticed any new bugs introduced to the application, but surely I'd be happy by more people testing this out and giving me feedback!

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [ ] All Tests within VisualStudio are passing
   - Option Page UI tests in VS are failing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [X] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by marcelmah** [comment]
I just downloaded this version: mRemoteNG-Portable-1.77.2.0.zip
I keep getting the popup when I run mRemoteNG.exe that I need .NET 5.0.0 and asking me to download, I did the first time and installed it (file: dotnet-runtime-5.0.9-win-x64.exe) even rebooted... but keep getting the question to install. Does it check for the exact version 5.0.0 as I have 5.0.9 ?

PS. glad to see this app is getting some new TLC, keep up the good work!

**Comment by farosch** [comment]
@marcelmah My guess is you need the [desktop runtime](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.9-windows-x64-installer)

**Comment by marcelmah** [comment]
> @marcelmah My guess is you need the [desktop runtime](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.9-windows-x64-installer)

Doh... your right. When you land on that page I looked at the Windows MacOS Linux headings and the three pictures underneath with different download links... never read the headings above the pictures, my bad!

I just installed the desktop version, now the error message is gone (can you change it so it's made clear you need the desktop download?, but now nothing happens when I start the app, no error in Windows log either, I did reboot (just to be sure) after installing ,NET 5 desktop.

**Comment by farosch** [comment]
@marcelmah By the time this will be released it will run on .NET6 and Microsoft will include it in future versions of Windows 10/11 -So no need to implement extra messages as these build are solely aimed at people trying to participate in the development of mRemoteNG.

Do you see the mRemoteNG.exe running in task manager?

**Comment by marcelmah** [comment]
> @marcelmah By the time this will be released it will run on .NET6 and Microsoft will include it in future versions of Windows 10/11 -So no need to implement extra messages as these build are solely aimed at people trying to participate in the development of mRemoteNG.
> 
> Do you see the mRemoteNG.exe running in task manager?

Ah alright.

I see mremoteng.exe for a couple of seconds in task manager, then it disappears,

**Comment by IDDesigns** [comment]
I'm just trying to update VNCSharp to .net 5 (https://github.com/IDDesigns/VncSharp/tree/ID/Net5) This is branched from https://github.com/mRemoteNG/VncSharp.

The first cut is project only changes, but I'm not sure of the best way to test the changes, any thoughts on this would be much appreciated.

**Comment by savornicesei** [comment]
I guess this is mergeable now 😄  https://dotnet.microsoft.com/download/dotnet/6.0

**Pull request merged**
