### PR TITLE
Added CEFSharp HTTP rendering engine

### PR DESCRIPTION
**Pull request by leaskovski**
Added the CEFSharp component to the project.  This is a Web rendering engine that is based on Chromium meaning that as well as being able to use IE and Gecko (Firefox), users will now also have the option to use CEF (Chromium) as their rendering engine.  This will mean the use of Chrome Remote Desktop as a URL can be used to provide connections to machines that use this protocol.

## Description
Added a new option to "Rendering Engine" called "CEF (Chromium)".  This requires CEF Sharp as being added to the project via nuget, and add a chromium based rendering engine to the application.
This covers the feature request #1071

## Motivation and Context
Chrome Remote Desktop is a protocol provided by Goolge to allow remote connections to machine.  This can be accessed via a website (https://remotedesktop.google.com/access), however this site (being Google) doesn't play well with other browsers, so neither the IE or Gecko engines work.  By adding CEF, the site renders fine and allows connections to machines hosted under this tool.

## How Has This Been Tested?
Basic testing has been completed by using the new engine for the original mentioned use case of Chrome Remote Desktop.
Tested under Windows 10 and Windows 7 environments.
Tested using Portable build only.
Tested persistence of logins to to site mentioned above.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] This pull request does not target the master branch.
- [x] I have updated the changelog file accordingly.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by leaskovski** [comment]
Note to whomever checks this... I am still not 100% got the hang of GIT so I am sorry if there is something wrong with this request.  Notice that there are merges from the main dev branch to my fork... Is this normal to see these in a pull request?

**Comment by leaskovski** [comment]
Also, another thing to check... The way the CEFSettings are setup and shutdown is currently in the main form.  This might not be a good place, so am expecting a request to change this.

**Comment by leaskovski** [comment]
Not sure why the build failed on "Installer.wixproj", as I have not made changes to this

**Comment by leaskovski** [comment]
Merged in the latest code of the develop branch to make this easier to get included into full releases.

**Comment by leaskovski** [comment]
Closing this pull request off as I am restructuring my fork as to where I did this work....

**Comment by fgroupindonesia** [comment]
cefsharp now support chrome remote desktop features?

**Pull request closed without merging**
