### PR TITLE
MR-421 The startup connection file could not be loaded

### PR DESCRIPTION
**Pull request by brucetp**
The actual problem is that the code was looking for a FileNotFoundException, which was never thrown.  I corrected that, plus added the recommended options of creating a new config file, selecting a custom path, as well as importing a file.  I haven't yet created Test cases so I'm not technically done, however I wanted to let you guys know I was working on it and give you a chance for feedback.

### CODE REVIEW

**Comment by brucetp** [comment]
This PR targets #421 obviously  :-)

**Comment by sparerd** [comment]
Nice, looking forward to it @brucetp! We are hoping to be feature-complete for v1.76 by Nov. 24. If this PR is done by then we will likely include it in that release

**Comment by brucetp** [comment]
Ok, Tests pass and added a new test.   Looks like all is working.

**Comment by brucetp** [comment]
Hey @sparerd, looks like jenkins is upset again because I added a file to the Test Project.   I'm done other than that.

**Comment by sparerd** [comment]
@brucetp Cool - could you pull the latest `develop` branch updates and merge those into your feature branch? It should prompt you to resolve the merge conflict.

**Comment by sparerd** [comment]
Looks good, thanks @brucetp! Merging

**Comment by steenstra** [comment]
The issue still exists:
image
image

**Pull request merged**
