### PR TITLE
Add Remote Desktop Manager (Devolutions) Importer

### PR DESCRIPTION
**Pull request by jonrainier**
## Description
Add support for migrating connections from Remote Desktop Manager (Devolutions)

In RDM: Right Click Connection Folder -> Export -> Export Special -> Export Selection (.csv)... -> enter password -> save the .ZIP -> Extract CSV from ZIP (will have password that you just entered) -> Import into mRemoteNG

## Motivation and Context
Allows importing CSV files generated by RDM to mRemoteNG.
- Add RDM Importer mRemoteNG/mRemoteNG#887

## How Has This Been Tested?
Tested and currently imports RDP / SSH connections

## Screenshots (if appropriate):
Screenshot of RDM Connection List
Screenshot of Import Button
Screenshot of Connections After Import

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Changed feature (non-breaking change which changes functionality)
- [ ] Changed feature (**breaking** change which changes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated translation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] All Tests within VisualStudio are passing
- [x] This pull request does not target the master branch.
- [ ] I have updated the changelog file accordingly, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by GCSmodell** [comment]
I followed the directions on v1.77.3 and get the error "Unable to import file.  File is empty."

**Comment by aaleks** [comment]
I followed the procedure I had exactly the same issue above 
image

Obviously the file is not empty.

**Comment by jonrainier** [comment]
QoL update by @Kvarkas broke it.

https://github.com/mRemoteNG/mRemoteNG/commit/ace62c07beae0dbc8b271aa97e2ea0ebd744f947#diff-89d8914acefb9ab6740c8e1c7f745d06d6653d4fa32dcf712ab1177728a1b7ffR32

Line 32 needs to be negated:

`if (string.IsNullOrEmpty(csvString))`
needs to be changed to
`if (!string.IsNullOrEmpty(csvString))`

Tested it locally and its still working!

**Comment by aaleks** [comment]
Thanks for the feedback I just opened an issue to track this bug

**Comment by Kvarkas** [comment]
thanks @pwnoz0r for pointing such, has been fixed. Sorry for delay, just come back after summer holidays.

**Comment by chmielo88** [comment]
Hi,

I followed the procedure without any errors but Imprted catalog is empty. My version of mRemoteNG: 1.77.3, version of RDM: 2022.1.25.0 64-bit.

image

**Pull request merged**
