### PR TITLE
[RFC] Added support for custom working directory in External Tool

### PR DESCRIPTION
**Pull request by pedro2555**
I'm closing #207 and as far as code goes, this is pretty much whats missing; can even be merged straight away with no backward compatibility issues.

But I'm unsure about 2 things:

1. What is `argParser.ParseArguments()` supposed to do? (I've peeked at the code, and it's no easy guess)

2. This, of course, would required adding UI elements to expose this, but just stumbled on [this bit of code](https://github.com/mRemoteNG/mRemoteNG/blob/Patch9/mRemoteV1/UI/Window/ExternalToolsWindow.cs#L196). My intention is to add a new input exactly as there is for _Arguments_, does this require any coordination or how does it work with the internationalisation part? (kinda lost here)
image

### CODE REVIEW

**Comment by pedro2555** [comment]
Implemented the whole UI, and the feature itself is ready to ship.

Just missing that internationalisation part I'm not really sure how to go about.

PS: while doing this, ended up finding fixing a small bug where the filename wasn't updated on the ExternalTool instance when changed via the file dialog _Browse_ button.

**Comment by sparerd** [comment]
Retargeted to `develop` branch

**Comment by sparerd** [comment]
@pedro2555 Here is a patch file for proposed changes to solve the merge issues that happened because of the retarget. Let me know if this works for you. Once the merge conflicts are resolved we can start testing and get this merged in

[pr706_patch.diff.txt](https://github.com/mRemoteNG/mRemoteNG/files/1459256/pr706_patch.diff.txt)

**Comment by sparerd** [comment]
Merging this into a custom branch off of `master`, it will still be included in v1.76

**Comment by sparerd** [comment]
This is now merged to the `develop` branch

**Pull request merged**
