### PR TITLE
MultiMonitor support

### PR DESCRIPTION
**Pull request by cveld**
As per https://github.com/mRemoteNG/mRemoteNG/issues/192 we have implemented multi-monitor support.
- Boolean option added to the `Appearance` panel
- Leveraging the interface ` IMsRdpClientNonScriptable5` and property `UseMultimon`

### CODE REVIEW

**Comment by cveld** [comment]
It looks like we are leveraging the wrong API here. We now get the Vista Spanned desktops in one window situation. We need to research a newer Windows 7 API.

**Comment by kmscode** [comment]
@cveld 
Thanks for the pull request! Taking a quick look at the code changes and they look OK... I will test and confirm accordingly.

>It looks like we are leveraging the wrong API here. We now get the Vista Spanned desktops in one window situation. We need to research a newer Windows 7 API.
Could you please clarify this comment further?

**Comment by btull89** [comment]
Thank you @cveld ! I've been waiting for this for awhile.
Can't wait for this to be released!

**Comment by btull89** [comment]
@kmscode Any idea when this will be released?

**Comment by kmscode** [comment]
@btull89 I don't have a solid ETA at the moment. However, I will say that it will be before (what is as of this writing) the 1.76 release. The 1.76 release has a huge feature (Credential Repository) which is a work in progress and requires a lot more work and testing before its ready for prime time....

So this PR will need to be merged into develop, then ported to the [Patch9 branch](https://github.com/mRemoteNG/mRemoteNG/tree/Patch9) that I'm working on. Rather than 1.75.7009, this will likely be renamed to 1.76 and 1.76 will get renamed to 1.77, etc... So sooner rather than later. I just don't have a solid timeline yet. I'll try to play less games and write more code at home (my 5yo insists that we save all Yoshi's friends in Woolly World). 😉

**Comment by btull89** [comment]
Thanks for the update! Don't rush it for the sake of me. Enjoy the time with your 5yo!!
I appreciate your work on this project.

**Comment by sgroner** [comment]
Any idea when this might be released.

**Comment by daniel-le9000** [comment]
Does anyone have a guide on how to implement this? For example which files to change the boolean value from false to true?

**Comment by daniel-le9000** [comment]
@sparerd @cveld @kmscode Does anyone have a guide on how to implement this? For example which files to change the boolean value from false to true?

**Comment by sparerd** [comment]
@daniel-le9000 The changes in this PR are a good starting point to get the basic functionality implemented. To ensure the property behaves correctly in other parts of the app, you will also need to make modifications in the areas I called out in my review comment above.

> - MultiMonitor is showing up in the config window for any tree node type. It should only be shown for connectioninfos or containerinfos whose protocol is "RDP". Look in mRemoteNG.UI.Window.ConfigWindow.ShowHideGridItems() for how to do this
> - Need to implement an inheritance property for MultiMonitor (mRemoteNG.Connection.ConnectionInfoInheritance)
> - Need to implement ConDefaultMultiMonitor and InhDefaultMultiMonitor in the Property\Settings.settings file to support serializing default connection info data for this property

In that comment I also forgot to mention that the serializers/deserializers need to be updated to include the property.

**Comment by sparerd** [comment]
Closing this PR in favor of #1150

**Pull request closed without merging**
