### PR TITLE
Sql fixes

### PR DESCRIPTION
**Pull request by Filippo125**
Change behaviour when sql database is used. 
## Description
 The changes to the dataset are made by performing an UPDATE (or DELETE) statement only for the row that are changed. 

## Motivation and Context
Everytime any data is updated and saved the program deletes all existing rows from tblCons and creates a full set of new rows. 

## How Has This Been Tested?
I tested it both on mysql and mssql server express

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
There is a nesting using in SqlDataProvider.
- [ ] All Tests within VisualStudio are passing
- [X] This pull request does not target the master branch.
- [X] I have updated the changelog file accordingly, if necessary.
- [X] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by farosch** [comment]
#1589 1589

**Comment by nLeonardt95** [comment]
Hello, 

I am also very interested in the change and have tested the version.

With version 1.77.1.28584 (Installer) or 1.77.1.28406 (Portable) I have the problem that the error message "VerifyDatabaseVersion (Config.Connections.Save) failed. Duplicate key name 'id'" comes.

I have also manually run the update for SqlVersion 2.8 from "mRemoteV1\Config\Serializers\Versioning\SqlVersion27To28Upgrader.cs". 
If you then start mRemoteNG for the first time everything works. 
However, as soon as you close mRemoteNG, the table "tblRoot" sets "ConfVersion" back to 2.7 and the error message "VerifyDatabaseVersion (Config.Connections.Save) failed. Duplicate key name 'id'" comes back.

**Comment by nLeonardt95** [comment]
Problem is in 
"mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\SqlDatabaseMetaDataRetriever.cs"

"WriteDatabaseMetaData"

ConnectionsFileInfo.ConnectionFileVersion is still 2.7

**Comment by Filippo125** [comment]
Which database are you using?

**Comment by nLeonardt95** [comment]
MySQL

**Pull request merged**
