### PR TITLE
Language fix

### PR DESCRIPTION
**Pull request by farosch**
See #785. (The string in the second picture was already is translated by now)
The text containing the update channels explaination was a standard TextBox, changed it to a NGLabel instead.

### CODE REVIEW

**Comment by farosch** [comment]
I moved the reconnect button from the tab context menu to the first position. It felt a little off in the middle of the tab handling options:
**Before:**
devenv_2018-12-24_21-31-21

**After:**
devenv_2018-12-24_21-31-59


Also "Disconnect Other Tabs" only shows up when there are actually other tabs and
"Disconnect Tabs to the right" only shows up when there are tabs to the right

**Comment by sparerd** [comment]
> I moved the reconnect button from the tab context menu to the first position. It felt a little off in the middle of the tab handling options:

It also feels weird having Reconnect/Disconnect in different places. "Duplicate Tab" is also essentially just "Duplicate Connection", which fits the theme of connection state management. The only one that doesn't really fit with that logic is Rename Tab.

**Comment by sparerd** [comment]
I'll concede that Duplicate and Rename Tab probably aren't used that often. Another option would be to move both the reconnect/disconnect stuff to the top.
```
Reconnect
Disconnect
Disconnect Other Tabs
Disconnect Tabs To The Right
----
Fullscreen (RDP)
...
```

**Comment by sparerd** [comment]
Though changing the location of those items really doesn't fit within this PR, since this is for fixing some localization issues.

**Comment by farosch** [comment]
Should I undo changing the icon position and make a new PR for this?

**Comment by sparerd** [comment]
Yes, that might be best

**Comment by farosch** [comment]
Closed, see #1229

**Pull request closed without merging**
