### PR TITLE
ReSharper: code cleanup

### PR DESCRIPTION
**Pull request by jumoog**
also fixing #168

### CODE REVIEW

**Comment by jumoog** [comment]
build works

**Comment by sparerd** [comment]
Thanks for submitting this PR!

Would you consider splitting this into multiple smaller PRs? Going through all +7k lines will take us a very long time. At the very least, the fix to #168 must be a separate PR to make it easier to evaluate.

(Don't worry about the Jenkins build failure. Our pipeline is having issues checking out PRs at the moment.)

**Comment by jumoog** [comment]
I'll split PR

**Comment by kmscode** [comment]
@jumoog - Yes! Thanks! 

However, please also note, that we use ReSharper as well. We tend to do smaller changes while we're in the files doing other things.

I have found that sometimes ReSharper will propose fixes and it will cause other problems despite build success and general run-ability of the resulting code. For example, some times adding the "@" to denote a literal string will cause the designer to throw an exception when trying to open that UI. Also, VS will just overwrite many of the changes to the Designer files.

**Pull request closed without merging**
